export default {
    API_URL: process.env.NEXT_PUBLIC_API_URL,
    CREATOR_LOGIN_PATH: process.env.NEXT_PUBLIC_CREATOR_LOGIN_PATH,
    CREATOR_SIGNUP_PATH: process.env.NEXT_PUBLIC_CREATOR_SIGNUP_PATH,
    FRONT_END_DOMAIN: process.env.NEXT_PUBLIC_FRONT_END_DOMAIN,
    FRONT_END_URL: process.env.NEXT_PUBLIC_FRONT_END_URL
};